/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_runs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Signals */
        get: operations["list_signals_api_signals_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/signals/{signal_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Signal Detail */
        get: operations["signal_detail_api_signals__signal_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sources": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sources */
        get: operations["list_sources_api_sources_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/summaries/{dimension}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Summarise */
        get: operations["summarise_api_summaries__dimension__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/themes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ranked */
        get: operations["ranked_api_themes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/trends/{dimension}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trend */
        get: operations["trend_api_trends__dimension__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AggregateSignal
         * @description A published statistic covering an observation window.
         */
        AggregateSignal: {
            /** Body */
            body: string;
            /** Category */
            category?: string | null;
            /** Denominator */
            denominator?: number | null;
            /** External Id */
            external_id: string;
            /** Extras */
            extras?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Firm Name */
            firm_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @default aggregate
             * @constant
             */
            kind: "aggregate";
            /**
             * Language
             * @default en
             */
            language: string;
            /**
             * Period End
             * Format: date
             */
            period_end: string;
            /**
             * Period Start
             * Format: date
             */
            period_start: string;
            provenance: components["schemas"]["Provenance"];
            /** Published At */
            published_at: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Key */
            source_key: string;
            /** Title */
            title: string | null;
            /** Upheld Share */
            upheld_share?: number | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
            /** Volume */
            volume: number;
        };
        /**
         * Cursor
         * @description Opaque to everything except the adapter that owns it.
         *
         *     The pipeline stores and replays `state` verbatim; only the adapter whose
         *     `source_key` matches interprets its contents.
         */
        Cursor: {
            /** Source Key */
            source_key: string;
            /** State */
            state?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionMethod
         * @enum {string}
         */
        IngestionMethod: "official_api" | "bulk_download" | "scrape" | "manual_import";
        /**
         * IngestionRun
         * @description Counts and cursor movement for a single run of one source.
         */
        IngestionRun: {
            cursor_after?: components["schemas"]["Cursor"] | null;
            cursor_before?: components["schemas"]["Cursor"] | null;
            /**
             * Deduplicated
             * @default 0
             */
            deduplicated: number;
            /** Errors */
            errors?: string[];
            /**
             * Fetched
             * @default 0
             */
            fetched: number;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Parsed
             * @default 0
             */
            parsed: number;
            /** Source Key */
            source_key: string;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /**
             * Stored New
             * @default 0
             */
            stored_new: number;
        };
        JsonValue: unknown;
        /**
         * Provenance
         * @description Every signal traces to an archived payload and the run that produced it.
         *
         *     The raw payload is stored write-once and content-addressed, so bumping an
         *     adapter's version and replaying the archive (`pf reparse`) can regenerate
         *     every signal without refetching anything.
         */
        Provenance: {
            /** Adapter Version */
            adapter_version: number;
            /**
             * Fetched At
             * Format: date-time
             */
            fetched_at: string;
            /**
             * Ingestion Run Id
             * Format: uuid
             */
            ingestion_run_id: string;
            /** Raw Payload Sha256 */
            raw_payload_sha256: string;
        };
        /** RankedTheme */
        RankedTheme: {
            /** Corroborating Sources */
            corroborating_sources: number;
            /** Previous Volume */
            previous_volume: number;
            /** Recent Volume */
            recent_volume: number;
            /** Severity Weighted */
            severity_weighted: number;
            /** Signals */
            signals: number;
            /** Theme */
            theme: string;
            /** Volume */
            volume: number;
        };
        /**
         * RateLimit
         * @description At most `requests` requests per `per_seconds` window.
         */
        RateLimit: {
            /**
             * Burst
             * @default 1
             */
            burst: number;
            /** Per Seconds */
            per_seconds: number;
            /** Requests */
            requests: number;
        };
        /**
         * RobotsStatus
         * @enum {string}
         */
        RobotsStatus: "allowed" | "disallowed" | "not_applicable";
        /**
         * SignalKind
         * @enum {string}
         */
        SignalKind: "verbatim" | "aggregate";
        /** SignalPage */
        SignalPage: {
            /** Items */
            items: (components["schemas"]["VerbatimSignal"] | components["schemas"]["AggregateSignal"])[];
            /** Limit */
            limit: number;
            /** Offset */
            offset: number;
            /** Total */
            total: number;
        };
        /** SourceInfo */
        SourceInfo: {
            /** Enabled */
            enabled: boolean;
            /** Key */
            key: string;
            last_run: components["schemas"]["IngestionRun"] | null;
            policy: components["schemas"]["SourcePolicy"];
            /** Version */
            version: number;
        };
        /**
         * SourcePolicy
         * @description One per adapter: how this source may lawfully be collected.
         *
         *     `terms_reviewed` is the date a human last read robots.txt and the site's
         *     terms; `terms_notes` records where they live and what they permit, so the
         *     review is auditable without leaving the code.
         */
        SourcePolicy: {
            method: components["schemas"]["IngestionMethod"];
            rate_limit: components["schemas"]["RateLimit"];
            /**
             * Requires Browser
             * @default false
             */
            requires_browser: boolean;
            robots_status: components["schemas"]["RobotsStatus"];
            /** Terms Notes */
            terms_notes: string;
            /**
             * Terms Reviewed
             * Format: date
             */
            terms_reviewed: string;
            /** User Agent */
            user_agent: string;
        };
        /**
         * SummaryDimension
         * @enum {string}
         */
        SummaryDimension: "category" | "firm" | "source";
        /** SummaryRow */
        SummaryRow: {
            /** Key */
            key: string;
            /** Signals */
            signals: number;
            /** Upheld Share */
            upheld_share: number | null;
            /** Volume */
            volume: number;
        };
        /** TrendPoint */
        TrendPoint: {
            /**
             * Bucket
             * Format: date
             */
            bucket: string;
            /** Key */
            key: string;
            /** Signals */
            signals: number;
            /** Volume */
            volume: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerbatimSignal
         * @description One person's own words, unmodified.
         */
        VerbatimSignal: {
            /** Author Handle */
            author_handle?: string | null;
            /** Body */
            body: string;
            /** Category */
            category?: string | null;
            /** External Id */
            external_id: string;
            /** Extras */
            extras?: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Firm Name */
            firm_name?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Kind
             * @default verbatim
             * @constant
             */
            kind: "verbatim";
            /**
             * Language
             * @default en
             */
            language: string;
            provenance: components["schemas"]["Provenance"];
            /** Published At */
            published_at: string | null;
            /**
             * Retrieved At
             * Format: date-time
             */
            retrieved_at: string;
            /** Source Key */
            source_key: string;
            /** Title */
            title: string | null;
            /**
             * Url
             * Format: uri
             */
            url: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_runs_api_runs_get: {
        parameters: {
            query?: {
                source_key?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionRun"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_signals_api_signals_get: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                source_key?: string | null;
                kind?: components["schemas"]["SignalKind"] | null;
                firm?: string | null;
                category?: string | null;
                period_from?: string | null;
                period_to?: string | null;
                search?: string | null;
                theme?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SignalPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    signal_detail_api_signals__signal_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                signal_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerbatimSignal"] | components["schemas"]["AggregateSignal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sources_api_sources_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceInfo"][];
                };
            };
        };
    };
    summarise_api_summaries__dimension__get: {
        parameters: {
            query?: {
                top?: number;
                source_key?: string | null;
                kind?: components["schemas"]["SignalKind"] | null;
                firm?: string | null;
                category?: string | null;
                period_from?: string | null;
                period_to?: string | null;
                search?: string | null;
                theme?: string | null;
            };
            header?: never;
            path: {
                dimension: components["schemas"]["SummaryDimension"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SummaryRow"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ranked_api_themes_get: {
        parameters: {
            query?: {
                top?: number;
                source_key?: string | null;
                kind?: components["schemas"]["SignalKind"] | null;
                firm?: string | null;
                category?: string | null;
                period_from?: string | null;
                period_to?: string | null;
                search?: string | null;
                theme?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankedTheme"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trend_api_trends__dimension__get: {
        parameters: {
            query?: {
                series?: number;
                source_key?: string | null;
                kind?: components["schemas"]["SignalKind"] | null;
                firm?: string | null;
                category?: string | null;
                period_from?: string | null;
                period_to?: string | null;
                search?: string | null;
                theme?: string | null;
            };
            header?: never;
            path: {
                dimension: components["schemas"]["SummaryDimension"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrendPoint"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
