"""signals full text search

Revision ID: 0bc45ac7ce81
Revises: 6b940de4d496
Create Date: 2026-07-25 12:21:03.340459
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0bc45ac7ce81"
down_revision: str | None = "6b940de4d496"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "signals",
        sa.Column(
            "search_tsv",
            postgresql.TSVECTOR(),
            sa.Computed(
                "to_tsvector('english', coalesce(title, '') || ' ' || body)", persisted=True
            ),
            nullable=False,
        ),
    )
    op.create_index(
        "ix_signals_search_tsv", "signals", ["search_tsv"], unique=False, postgresql_using="gin"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_signals_search_tsv", table_name="signals", postgresql_using="gin")
    op.drop_column("signals", "search_tsv")
    # ### end Alembic commands ###
