"""add theme_suggestions

Revision ID: 8d54993a4dc2
Revises: f33c3d6402e4
Create Date: 2026-07-25 18:17:33.811591
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "8d54993a4dc2"
down_revision: str | None = "f33c3d6402e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "theme_suggestions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("cluster_key", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=128), nullable=False),
        sa.Column("top_terms", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("size", sa.Integer(), nullable=False),
        sa.Column("member_signal_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "representative_signal_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("suggested_theme", sa.String(length=128), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("mapped_theme", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_theme_suggestions")),
    )
    op.create_index(
        op.f("ix_theme_suggestions_method"), "theme_suggestions", ["method"], unique=False
    )
    op.create_index(
        op.f("ix_theme_suggestions_status"), "theme_suggestions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_theme_suggestions_status"), table_name="theme_suggestions")
    op.drop_index(op.f("ix_theme_suggestions_method"), table_name="theme_suggestions")
    op.drop_table("theme_suggestions")
    # ### end Alembic commands ###
