"""initial schema

Revision ID: b9e7867a66a4
Revises:
Create Date: 2026-07-25 10:34:54.603429
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b9e7867a66a4"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cursor_before", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cursor_after", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("fetched", sa.Integer(), nullable=False),
        sa.Column("parsed", sa.Integer(), nullable=False),
        sa.Column("stored_new", sa.Integer(), nullable=False),
        sa.Column("deduplicated", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ingestion_runs")),
    )
    op.create_index(
        op.f("ix_ingestion_runs_source_key"), "ingestion_runs", ["source_key"], unique=False
    )
    op.create_table(
        "raw_payloads",
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("relative_path", sa.String(), nullable=False),
        sa.Column("adapter_version", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("sha256", name=op.f("pk_raw_payloads")),
    )
    op.create_index(
        op.f("ix_raw_payloads_source_key"), "raw_payloads", ["source_key"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("external_id", sa.String(length=256), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retrieved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("language", sa.String(length=16), nullable=False),
        sa.Column("firm_name", sa.String(length=256), nullable=True),
        sa.Column("category", sa.String(length=128), nullable=True),
        sa.Column("extras", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("author_handle", sa.String(length=128), nullable=True),
        sa.Column("period_start", sa.Date(), nullable=True),
        sa.Column("period_end", sa.Date(), nullable=True),
        sa.Column("volume", sa.Integer(), nullable=True),
        sa.Column("upheld_share", sa.Float(), nullable=True),
        sa.Column("denominator", sa.Integer(), nullable=True),
        sa.Column("raw_payload_sha256", sa.String(length=64), nullable=False),
        sa.Column("adapter_version", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Uuid(), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("dedupe_hash", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(
            ["ingestion_run_id"],
            ["ingestion_runs.id"],
            name=op.f("fk_signals_ingestion_run_id_ingestion_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["raw_payload_sha256"],
            ["raw_payloads.sha256"],
            name=op.f("fk_signals_raw_payload_sha256_raw_payloads"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
        sa.UniqueConstraint("source_key", "external_id", name=op.f("uq_signals_source_key")),
    )
    op.create_index(op.f("ix_signals_category"), "signals", ["category"], unique=False)
    op.create_index(op.f("ix_signals_dedupe_hash"), "signals", ["dedupe_hash"], unique=False)
    op.create_index(op.f("ix_signals_firm_name"), "signals", ["firm_name"], unique=False)
    op.create_index(op.f("ix_signals_kind"), "signals", ["kind"], unique=False)
    op.create_index(op.f("ix_signals_source_key"), "signals", ["source_key"], unique=False)
    op.create_table(
        "signal_enrichments",
        sa.Column("signal_id", sa.Uuid(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("theme", sa.String(length=128), nullable=True),
        sa.Column("sub_theme", sa.String(length=128), nullable=True),
        sa.Column("product_domain", sa.String(length=64), nullable=True),
        sa.Column("severity", sa.Float(), nullable=True),
        sa.Column("severity_basis", sa.String(), nullable=True),
        sa.Column("monetary_amount", sa.Numeric(precision=14, scale=2), nullable=True),
        sa.Column("monetary_currency", sa.String(length=3), nullable=True),
        sa.Column("resolution", sa.String(length=32), nullable=True),
        sa.Column("geography", sa.String(length=16), nullable=True),
        sa.Column("segment", sa.String(length=32), nullable=True),
        sa.Column("sentiment", sa.Float(), nullable=True),
        sa.Column("method", sa.String(length=64), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["signal_id"], ["signals.id"], name=op.f("fk_signal_enrichments_signal_id_signals")
        ),
        sa.PrimaryKeyConstraint("signal_id", "version", name=op.f("pk_signal_enrichments")),
    )
    op.create_index(
        op.f("ix_signal_enrichments_product_domain"),
        "signal_enrichments",
        ["product_domain"],
        unique=False,
    )
    op.create_index(
        op.f("ix_signal_enrichments_theme"), "signal_enrichments", ["theme"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_signal_enrichments_theme"), table_name="signal_enrichments")
    op.drop_index(op.f("ix_signal_enrichments_product_domain"), table_name="signal_enrichments")
    op.drop_table("signal_enrichments")
    op.drop_index(op.f("ix_signals_source_key"), table_name="signals")
    op.drop_index(op.f("ix_signals_kind"), table_name="signals")
    op.drop_index(op.f("ix_signals_firm_name"), table_name="signals")
    op.drop_index(op.f("ix_signals_dedupe_hash"), table_name="signals")
    op.drop_index(op.f("ix_signals_category"), table_name="signals")
    op.drop_table("signals")
    op.drop_index(op.f("ix_raw_payloads_source_key"), table_name="raw_payloads")
    op.drop_table("raw_payloads")
    op.drop_index(op.f("ix_ingestion_runs_source_key"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
