"""add cursors table

Revision ID: f33c3d6402e4
Revises: 0bc45ac7ce81
Create Date: 2026-07-25 15:45:27.173318
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f33c3d6402e4"
down_revision: str | None = "0bc45ac7ce81"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cursors",
        sa.Column("source_key", sa.String(length=64), nullable=False),
        sa.Column("state", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("source_key", name=op.f("pk_cursors")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cursors")
    # ### end Alembic commands ###
